[target.x86_64-unknown-linux-gnu]

[target.thumbv7m-none-eabi]
runner = 'arm-none-eabi-gdb'
# rustflags = [
#   "-C", "link-arg=-Tlink.x",
#   "-C", "linker=cortex-m-rt-ld", # <- CHANGED!
#   "-Z", "linker-flavor=ld",
#   "-Z", "thinlto=no",
# ]

[build]
target = "x86_64-unknown-linux-gnu"
# target = "thumbv7m-none-eabi"
